apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongo-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store         # must match SecretStore name
    kind: SecretStore
  target:
    name: mongo-secret             # the name of the Kubernetes Secret created
    creationPolicy: Owner
  data:
    - secretKey: MONGO_USER
      remoteRef:
        key: my-nodeapp/mongo-credentials
        property: username
    - secretKey: MONGO_PASSWORD
      remoteRef:
        key: my-nodeapp/mongo-credentials
        property: password
